### ISSUE TITLE
findDOMElementForTrack isn't useful

### ISSUE THREAD

**Issue by phsultan** [livestorm/webrtc-publisher-stats#1]
We try to match the `MediaTracks` of the `RTCRtpSenders` obtained from the active `RTCPeerConnections` with `MediaStreams` in the DOM by searching for `<video/>` and `<audio/>` elements.

This approach seems wrong because it does not work in the case of Google Meet where we fail to display the audio stats because we can't find such a match.

I think we should just remove the `findDOMElementForTrack` and use another identifier for the tracks of the `RTCRtpSenders` than the `MediaStream` ID of the DOM element that has been found.

@lmangani you spotted this before, please let me know if I missed something here, thanks!

**Comment by lmangani** [comment]
I believe one of the working approaches around is overriding and intercept the getUserMedia calls. One example is ObserveRTC which I'm quite sure uses this - Have you considered this route already?

**Comment by phsultan** [comment]
No, but that would work for sure. Would you like to give it a shot or should I just take a look?

**Comment by phsultan** [comment]
Latest updates fixed this.
